# Generated by Django 5.1 on 2025-04-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bathroom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
    ]
