# Generated by Django 5.2 on 2025-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reststop_rater', '0003_review_unique_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='gmaps_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
