# Generated by Django 5.2 on 2025-04-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0004_bathroom_gmaps_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bathroom",
            name="gmaps_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
