# Generated by Django 5.2 on 2025-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0005_alter_bathroom_gmaps_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bathroom",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
