# Generated by Django 5.2 on 2025-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0006_bathroom_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bathroom",
            name="report_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bathroom",
            name="report_yes",
            field=models.IntegerField(default=0),
        ),
    ]
