# Generated by Django 5.2 on 2025-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0007_bathroom_report_no_bathroom_report_yes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bathroom",
            name="quick_rate",
            field=models.JSONField(default=dict),
        ),
    ]
