# Generated by Django 5.2 on 2025-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reststop_rater', '0008_bathroom_quick_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
