# Generated by Django 5.2 on 2025-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reststop_rater', '0009_alter_bathroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
