# Generated by Django 5.1 on 2025-04-19 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reststop_rater", "0002_alter_bathroom_options_alter_review_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "bathroom"), name="unique_user_review"
            ),
        ),
    ]
